<?php
/*
  Downloadable CSV costing report for one shipment — runs the same Stage-1
  deterministic engine as the on-screen AI Check panel (includes/ai_check_core.php),
  independently of whether AI Check has ever been clicked for this shipment.
  Shows exactly how material cost/qty and line profitability were calculated,
  plus every rule finding, so figures can be checked line by line.
*/
require_once __DIR__ . '/includes/bootstrap.php';
require_once __DIR__ . '/includes/pm_search.php';
require_once __DIR__ . '/includes/ai_check_core.php';
require_login();

if (!is_admin()) { http_response_code(403); exit('Costing report is available to Admin only.'); }

$id = (int)($_GET['id'] ?? 0);
$result = ai_check_compute($id);
if (!$result) { http_response_code(404); exit('Shipment not found.'); }

$s = $result['shipment'];
$cur = $s['currency'] ?: 'PKR';
$fname = 'costing_report_' . preg_replace('/[^A-Za-z0-9_\-]/', '_', $s['invoice_no'] ?: ('shipment_' . $id)) . '.csv';

header('Content-Type: text/csv; charset=utf-8');
header('Content-Disposition: attachment; filename="' . $fname . '"');
header('Pragma: no-cache');
header('Expires: 0');

$out = fopen('php://output', 'w');
fwrite($out, "\xEF\xBB\xBF"); // UTF-8 BOM so Excel shows PKR "₨" / Urdu text correctly

fputcsv($out, ['ZAS Textile — Costing & AI Check Report']);
fputcsv($out, ['Invoice No', $s['invoice_no']]);
fputcsv($out, ['Buyer', $s['buyer_name']]);
fputcsv($out, ['Country', $s['buyer_country'] ?? '']);
fputcsv($out, ['Currency', $cur]);
fputcsv($out, ['Invoice Date', $s['invoice_date'] ?? '']);
fputcsv($out, ['Status', ucwords(str_replace('_', ' ', $s['status']))]);
fputcsv($out, ['Generated', date('Y-m-d H:i')]);
fputcsv($out, ['Generated By', current_user()['name'] ?? '']);
fputcsv($out, []);

fputcsv($out, ['LINE ITEMS — COSTING DETAIL']);
fputcsv($out, ['Line', 'Product (Invoice)', 'Description', 'Qty', 'Unit', 'Rate', 'Sales Amount', 'Matched Product (Master)', 'Found in Master', 'Costing Version Used', 'Size Matched', 'Unit Cost', 'Line Cost', 'Gross Profit', 'Margin %', 'Note']);
foreach ($result['line_costing'] as $lc) {
    fputcsv($out, [
        $lc['line'], $lc['product_name'], $lc['description'], $lc['qty'], $lc['unit'], $lc['rate'], $lc['sales_amount'],
        $lc['matched_product'], $lc['master_found'] ? 'Yes' : 'No', $lc['costing_version'],
        $lc['size_matched'] === null ? '' : ($lc['size_matched'] ? 'Yes' : 'No'),
        $lc['unit_cost'] ?? '', $lc['line_cost'] ?? '', $lc['gross_profit'] ?? '', $lc['margin_pct'] ?? '',
        $lc['note'],
    ]);
}
fputcsv($out, []);

fputcsv($out, ['MATERIAL UTILISATION — AGGREGATE ACROSS ALL LINES (same category+material+unit combined into one row, regardless of price)']);
fputcsv($out, ['Category', 'Material', 'Unit', 'Qty Used (total)', 'Weight Total (kg)', "Cost ({$cur})"]);
foreach ($result['materials'] as $m) {
    fputcsv($out, [$m['category'], $m['material'], $m['unit'], round($m['qty'], 3), round($m['wt'] ?? 0, 3), round($m['cost'], 2)]);
}
fputcsv($out, []);

$f = $result['financials']; $c = $result['container'];
fputcsv($out, ['SUMMARY']);
fputcsv($out, ["Sales Total ({$cur})", $f['sales_total']]);
fputcsv($out, ["Estimated Cost Total ({$cur})", $f['estimated_cost_total'], $f['cost_complete'] ? '' : '(PARTIAL — costing missing for some products)']);
fputcsv($out, ["Gross Profit ({$cur})", $f['gross_profit']]);
fputcsv($out, ['Gross Margin %', $f['gross_margin_percent']]);
fputcsv($out, ['Sales Total (PKR equiv.)', $f['sales_total_pkr']]);
fputcsv($out, ['Cost Total (PKR equiv.)', $f['estimated_cost_total_pkr']]);
fputcsv($out, ['Gross Profit (PKR equiv.)', $f['gross_profit_pkr']]);
fputcsv($out, ['Est. Volume (CBM)', $c['cbm']]);
fputcsv($out, ['Suggested Container', $c['type'] ?: '—', $c['utilisation'] ? $c['utilisation'] . '% utilised' : '']);
fputcsv($out, ['AI Check Score', $result['score'] . '/100']);
fputcsv($out, ['Errors', $result['counts']['errors']]);
fputcsv($out, ['Warnings', $result['counts']['warnings']]);
fputcsv($out, ['Info', $result['counts']['info']]);
fputcsv($out, []);

fputcsv($out, ['ALL FINDINGS (same checks as the on-screen AI Check panel)']);
fputcsv($out, ['Level', 'Code', 'Line', 'Message']);
foreach ($result['checks'] as $chk) {
    fputcsv($out, [strtoupper($chk['level']), $chk['code'], $chk['line_no'] ?? '', $chk['msg']]);
}

fclose($out);
